USE NewsDB
GO

ALTER TRIGGER [dbo].[TRIGGER_DATE_NEWS_CREATE]
  ON [dbo].[News]
  AFTER INSERT
  AS
BEGIN
  UPDATE [dbo].[News]
    SET CreateDate = GETDATE()
END

GO

ALTER TRIGGER [dbo].[TRIGGER_DATE_NEWS_UPDATE] 
ON [dbo].[News]
AFTER UPDATE
AS
BEGIN 
IF NOT EXISTS(SELECT * FROM INSERTED) OR (TRIGGER_NESTLEVEL() > 1)
    RETURN;
  UPDATE [dbo].[News]
    SET ModDate = GETDATE()
	FROM DELETED OLD
  WHERE [News].ID IN (SELECT ID FROM INSERTED);
END

GO

ALTER TRIGGER [dbo].[TRIGGER_DATE_USER_CREATE]
  ON [dbo].[User]
  AFTER INSERT
  AS
BEGIN
  UPDATE [dbo].[User]
    SET CreateDate = GETDATE(),
		IsActive = 'true'
END

GO

ALTER TRIGGER [dbo].[TRIGGER_DATE_USER_UPDATE]
  ON [dbo].[User]
  AFTER UPDATE
  AS
BEGIN
  IF NOT EXISTS(SELECT * FROM INSERTED) OR (TRIGGER_NESTLEVEL() > 1)
    RETURN;
  UPDATE [dbo].[User]
    SET ModDate = GETDATE()
	FROM DELETED OLD
  WHERE [User].ID IN (SELECT ID FROM INSERTED);
END